import type { Order, Payment, StaffUser, Table } from '../shared/operations/operations.types';

export const adminPosStaff: StaffUser[] = [
  { id: 'staff-w-01', name: 'Laura Rojas', role: 'waiter', isActive: true },
  { id: 'staff-w-02', name: 'Daniel Mena', role: 'waiter', isActive: true },
  { id: 'staff-c-01', name: 'Sofía Gómez', role: 'cashier', isActive: true },
  { id: 'staff-a-01', name: 'Julián Rivera', role: 'admin', isActive: true },
];

export const adminPosTables: Table[] = [
  {
    id: 'table-01',
    code: 'M-01',
    name: 'Mesa 01',
    type: 'fixed',
    zone: 'salon',
    capacity: 4,
    status: 'available',
  },
  {
    id: 'table-05',
    code: 'M-05',
    name: 'Mesa 05',
    type: 'fixed',
    zone: 'salon',
    capacity: 4,
    status: 'occupied',
    assignedStaffUserId: 'staff-w-01',
    activeOrderId: 'order-05',
  },
  {
    id: 'table-t02',
    code: 'T-02',
    name: 'Terraza 02',
    type: 'fixed',
    zone: 'terrace',
    capacity: 2,
    status: 'occupied',
    assignedStaffUserId: 'staff-w-02',
    activeOrderId: 'order-t02',
  },
  {
    id: 'table-v01',
    code: 'VIP-01',
    name: 'Mesa VIP',
    type: 'fixed',
    zone: 'vip',
    capacity: 6,
    status: 'reserved',
    notes: 'Reserva confirmada para las 9:00 PM.',
  },
  {
    id: 'table-x1',
    code: 'AD-01',
    name: 'Mesa adicional A',
    type: 'temporary',
    zone: 'bar',
    capacity: 3,
    status: 'occupied',
    assignedStaffUserId: 'staff-w-01',
    activeOrderId: 'order-x1',
    notes: 'Mesa extra habilitada por alta ocupación.',
  },
];

export const adminPosOrders: Order[] = [
  {
    id: 'order-05',
    tableId: 'table-05',
    status: 'open',
    openedAt: '2026-05-05T19:10:00-05:00',
    openedByUserId: 'staff-w-01',
    assignedStaffUserId: 'staff-w-01',
    cashierUserId: 'staff-c-01',
    items: [
      {
        id: 'order-05-item-1',
        productName: 'Margaritas',
        quantity: 2,
        unitPrice: 22000,
        totalPrice: 44000,
        status: 'active',
        addedAt: '2026-05-05T19:12:00-05:00',
        addedByUserId: 'staff-w-01',
      },
      {
        id: 'order-05-item-2',
        productName: 'Papas rústicas',
        quantity: 1,
        unitPrice: 18000,
        totalPrice: 18000,
        status: 'active',
        addedAt: '2026-05-05T19:16:00-05:00',
        addedByUserId: 'staff-w-01',
      },
    ],
    paymentSummary: {
      subtotal: 62000,
      totalDue: 62000,
      totalPaid: 0,
      remainingBalance: 62000,
    },
    notes: 'Primera ronda servida.',
  },
  {
    id: 'order-t02',
    tableId: 'table-t02',
    status: 'partially_paid',
    openedAt: '2026-05-05T20:00:00-05:00',
    openedByUserId: 'staff-w-02',
    assignedStaffUserId: 'staff-w-02',
    cashierUserId: 'staff-c-01',
    items: [
      {
        id: 'order-t02-item-1',
        productName: 'Hawaiian Blue',
        quantity: 2,
        unitPrice: 26000,
        totalPrice: 52000,
        status: 'active',
        addedAt: '2026-05-05T20:02:00-05:00',
        addedByUserId: 'staff-w-02',
      },
      {
        id: 'order-t02-item-2',
        productName: 'Nachos Zafiro',
        quantity: 1,
        unitPrice: 24000,
        totalPrice: 24000,
        status: 'active',
        addedAt: '2026-05-05T20:08:00-05:00',
        addedByUserId: 'staff-w-02',
      },
    ],
    paymentSummary: {
      subtotal: 76000,
      totalDue: 76000,
      totalPaid: 30000,
      remainingBalance: 46000,
    },
    notes: 'Cliente solicita dividir la cuenta.',
  },
  {
    id: 'order-x1',
    tableId: 'table-x1',
    status: 'open',
    openedAt: '2026-05-05T21:05:00-05:00',
    openedByUserId: 'staff-w-01',
    assignedStaffUserId: 'staff-w-01',
    cashierUserId: 'staff-c-01',
    items: [
      {
        id: 'order-x1-item-1',
        productName: 'Micheladas',
        quantity: 3,
        unitPrice: 21000,
        totalPrice: 63000,
        status: 'active',
        addedAt: '2026-05-05T21:06:00-05:00',
        addedByUserId: 'staff-w-01',
      },
    ],
    paymentSummary: {
      subtotal: 63000,
      totalDue: 63000,
      totalPaid: 0,
      remainingBalance: 63000,
    },
    notes: 'Mesa temporal activa por evento de cumpleaños.',
  },
];

export const adminPosPayments: Payment[] = [
  {
    id: 'payment-t02-1',
    orderId: 'order-t02',
    amount: 30000,
    method: 'cash',
    status: 'confirmed',
    receivedAt: '2026-05-05T20:35:00-05:00',
    receivedByUserId: 'staff-c-01',
    confirmedAt: '2026-05-05T20:35:00-05:00',
    confirmedByUserId: 'staff-c-01',
    allocations: [
      {
        id: 'payment-t02-1-allocation',
        type: 'amount',
        amount: 30000,
      },
    ],
    amountDue: 76000,
    amountApplied: 30000,
    amountReceived: 50000,
    changeDue: 20000,
    cashDetails: {
      amountDue: 76000,
      amountApplied: 30000,
      amountReceived: 50000,
      changeDue: 20000,
    },
  },
  {
    id: 'payment-05-1',
    orderId: 'order-05',
    amount: 62000,
    method: 'nequi',
    status: 'pending',
    receivedAt: '2026-05-05T21:18:00-05:00',
    receivedByUserId: 'staff-c-01',
    allocations: [
      {
        id: 'payment-05-1-allocation',
        type: 'amount',
        amount: 62000,
      },
    ],
    amountDue: 62000,
    amountApplied: 62000,
    reference: 'NEQ-784211',
    notes: 'Pendiente confirmar transferencia en caja.',
  },
];
